# Generated by Django 3.0.6 on 2020-06-27 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20200627_1611'),
        ('multistepform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formmessage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='formmessage',
            name='subject',
        ),
        migrations.AddField(
            model_name='formmessage',
            name='additional_message',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='FormSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('are_you_happy', models.BooleanField()),
                ('do_you_know_it', models.BooleanField()),
                ('customer', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to='general.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
